"""AI-generated part models."""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, field_validator

from musicgen.ai_models.notes import AINote, AINoteEvent, AIRest


class InstrumentRole(str, Enum):
    """Role of an instrument in the composition."""
    MELODY = "melody"
    HARMONY = "harmony"
    BASS = "bass"
    ACCOMPANIMENT = "accompaniment"
    COUNTERMELODY = "countermelody"
    PAD = "pad"
    PERCUSSION = "percussion"


class AIPart(BaseModel):
    """An instrument part generated by AI.

    Contains a sequence of notes for a single instrument.
    """

    # Instrument identification
    name: str = Field(
        ...,
        description="Instrument name (e.g., 'violin', 'piano', 'flute')"
    )
    midi_program: int = Field(
        ...,
        description="MIDI program number (0-127)",
        ge=0,
        le=127
    )
    midi_channel: int = Field(
        default=0,
        description="MIDI channel (0-15, 10 for percussion)",
        ge=0,
        le=15
    )

    # Role
    role: InstrumentRole = Field(
        default=InstrumentRole.MELODY,
        description="Role this part plays in the composition"
    )

    # Notes - can be dict (from JSON) or AINoteEvent (already parsed)
    notes: list[dict | AINote | AIRest] = Field(
        default_factory=list,
        description="List of note/rest objects"
    )

    # Optional dynamics
    dynamics_marking: str | None = Field(
        None,
        description="Dynamic marking (pp, p, mp, mf, f, ff, fff)"
    )
    volume_adjustment: int = Field(
        default=0,
        description="Volume adjustment in decibels (-127 to 127)",
        ge=-127,
        le=127
    )

    # Optional articulation defaults
    default_articulation: str | None = Field(
        None,
        description="Default articulation for notes in this part"
    )

    @field_validator("notes", mode="before")
    @classmethod
    def validate_notes(cls, v: list) -> list:
        """Validate and convert note dictionaries."""
        validated = []
        for note in v:
            if isinstance(note, dict):
                # Check if it's a rest
                if note.get("rest") is True:
                    validated.append(AIRest(**note))
                else:
                    validated.append(AINote(**note))
            else:
                validated.append(note)
        return validated

    def get_note_events(self) -> list[AINoteEvent]:
        """Get validated note events.

        Returns:
            List of AINote and AIRest objects
        """
        events = []
        for note in self.notes:
            if isinstance(note, dict):
                if note.get("rest") is True:
                    events.append(AIRest(**note))
                else:
                    events.append(AINote(**note))
            elif isinstance(note, (AINote, AIRest)):
                events.append(note)
        return events

    @property
    def duration_quarters(self) -> float:
        """Get total duration in quarter notes.

        Returns:
            Total duration
        """
        return sum(
            n.duration if hasattr(n, "duration") else 0
            for n in self.get_note_events()
        )
